# inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/FrozenStringLiteralComment:
    Enabled: false
Style/Documentation:
    Enabled: false
Naming/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
Style/ClassAndModuleChildren:
  Enabled: false
